#%RAML 1.0
title: DATE-API
version: v1
baseUri: http://localhost:8081
types:
  Foramted_Date:
    properties:
      date: string

/date:
  get:
    description: Transform Date
    queryParameters:
      day_week: number
      day_month: number
      month: number
      year: number
    responses:
        200:
          body:
            application/json:
              type: Foramted_Date
              example: { "date": "Monday, March 12, 2019" }